### ISSUE TITLE
Error in angle shift

### ISSUE THREAD

**Issue by Snieffy** [the0b/MSP430-CORDIC-sine-cosine#2]
There is an error in the angle shift, resulting in wrong signs for return values **< -180** and  **> 180**.
We need to add **360** when **theta < -180** and subtract **360** when **theta > 180**.

``` C
  //Shift angle to be in range -180 to 180
  while(theta < -180) theta += 180;
  while(theta > 180) theta -= 180;
```

needs to be changed into

``` C
  //Shift angle to be in range -180 to 180
  while(theta < -180) theta += 360;
  while(theta > 180) theta -= 360;
```

**Comment by the0b** [comment]
Hadn't logged in to github for a long time. Committed your fix, thanks!
